#!/bin/bash
set -e;

[ $# -lt 2 ] &&
echo "Usage: ${0##*/} [options] <fst-rspecifier> <fst-wspecifier>" >&2 &&
exit 1;

opts=();
while [ $# -gt 2 ]; do
  opts+=("$1");
  shift;
done;

cmd="fstcompile | fstdeterminizestar --print-args=false ${opts[@]} | fstprint";
fstcopy --print-args=false "$1" "ark,t:-" |
awk -v cmd="$cmd" 'BEGIN{
  key="";
  buffer="";
}{
  if (key == "" && NF == 1) {
    key = $1;
    buffer = "";
    next;
  }

  if (NF == 0) {
    print key;
    print buffer | cmd;
    close(cmd);
    print "";

    key = "";
    buffer = "";
    next;
  }

  buffer = buffer""$0"\n";
}END{
  if (key != "") {
    print key;
    print buffer | cmd;
    close(cmd);
    print "";
  }
}' | fstcopy --print-args=false ark:- "$2";
